In [1]:
import numpy as np 
import pandas as pd

In [2]:
data=pd.read_csv('iris.csv')

In [3]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
Id               150 non-null int64
SepalLengthCm    150 non-null float64
SepalWidthCm     150 non-null float64
PetalLengthCm    150 non-null float64
PetalWidthCm     150 non-null float64
Species          150 non-null object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.1+ KB


In [9]:
data['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [10]:
data['Species'].replace({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2},inplace=True)

In [12]:
data['Species'].unique()

array([0, 1, 2], dtype=int64)

In [17]:
# Data we need for input our algorithm is always 2D data in arrays form. '.values' return values of each row in array form.
# here input columns are column 2 to 5
X=data.iloc[:,1:-1].values

In [20]:
X

numpy.ndarray

In [21]:
# Data we need for output our algorithm is always 1D data in arrays form.
y=data.iloc[:,-1].values

In [25]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [26]:
# Cross Validation -- How we will confirm that our ML model is working correctly.
# Thats why 80% data is for train and 20% is for test

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=.2)

In [29]:
X_test.shape

(30, 4)

In [30]:
y_test.shape

(30,)

In [31]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()

In [32]:
classifier.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [34]:
y_pred=classifier.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(y_test,y_pred)

0.8333333333333334

In [38]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [43]:
x_test=np.array([[1.5,1.6,2.1,2.6]])

In [44]:
y=classifier.predict(x_test)

In [45]:
y

array([2], dtype=int64)

In [57]:
# Function to predict and gives the species name.
def output(sw,sl,pw,pl):
    dic={0:'Iris-setosa',1:'Iris-versicolor',2:'Iris-virginica'}
    t= classifier.predict(np.array([sw,sl,pw,pl]).reshape(1,4))[0]
    return dic[t]

In [58]:
output(1.5,2.3,4.2,.7)

'Iris-setosa'

In [50]:
data['Species'].unique()

array([0, 1, 2], dtype=int64)

In [60]:
p=np.array([1])